rm: cannot remove '372_BRAVEHEART.tmp.out': No such file or directory
Traceback (most recent call last):
  File "get_combined_score.py", line 1023, in <module>
    main()
  File "get_combined_score.py", line 699, in main
    rnn = open("%s.RNN.tab_tmp" %molname)
IOError: [Errno 2] No such file or directory: '372_BRAVEHEART.RNN.tab_tmp'

real	0m36.989s
user	0m14.154s
sys	0m5.295s
mv: cannot strm: cannot remove '372_BRAVEHEART.tmp.out': No such file or directory

real	0m22.486s
user	0m12.912s
sys	0m3.848s

real	0m0.158s
user	0m0.124s
sys	0m0.028s

real	0m6.068s
user	0m6.013s
sys	0m0.048s

real	0m1.712s
user	0m1.093s
sys	0m0.611s
Read 1 item

real	39m5.663s
user	38m50.823s
sys	0m14.016s

real	0m2.964s
user	0m2.909s
sys	0m0.028s

real	0m1.326s
user	0m0.828s
sys	0m0.494s
Read 1 item

real	39m38.123s
user	39m22.691s
sys	0m14.133s

real	0m11.116s
user	0m11.029s
sys	0m0.064s

real	0m2.128s
user	0m1.627s
sys	0m0.496s
Read 1 item

real	39m40.140s
user	39m24.317s
sys	0m14.392s

real	0m4.316s
user	0m4.261s
sys	0m0.032s

real	0m0.956s
user	0m0.444s
sys	0m0.508s
Read 1 item

real	40m15.269s
user	40m0.200s
sys	0m13.523s

real	0m14.078s
user	0m13.976s
sys	0m0.044s

real	0m1.227s
user	0m0.727s
sys	0m0.495s
Read 1 item

real	40m11.829s
user	39m52.615s
sys	0m14.837s

real	0m9.360s
user	0m9.307s
sys	0m0.040s

real	0m2.028s
user	0m1.588s
sys	0m0.436s
Read 1 item

real	27m9.731s
user	26m57.768s
sys	0m10.030s

real	0m4.798s
user	0m4.748s
sys	0m0.024s

real	0m1.048s
user	0m0.558s
sys	0m0.486s
Read 1 item

real	40m38.160s
user	40m18.443s
sys	0m14.781s

real	0m6.130s
user	0m6.077s
sys	0m0.028s

real	0m1.544s
user	0m1.032s
sys	0m0.508s
Read 1 item

real	39m16.725s
user	39m0.726s
sys	0m14.484s
s)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: [Errno 2] File 372_BRAVEHEART.RNN_NP_ONLY.csv does not exist: '372_BRAVEHEART.RNN_NP_ONLY.csv'

real	0m0.049s
user	0m0.024s
sys	0m0.024s
split: cannot open '372_BRAVEHEART.SHAPE' for reading: No such file or directory
ls: cannot access '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/23_degrees/372_BRAVEHEART_23_180_60/res/splited_*': No such file or directory
mv: cannot stat '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/23_degrees/372_BRAVEHEART_23_180_60/res/*_*.SHAPE': No such file or directory
ls: cannot access '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/23_degrees/372_BRAVEHEART_23_180_60/final/*SHAPE': No such file or directory
ls: cannot access '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/23_degrees/372_BRAVEHEART_23_180_60/final/*.ct': No such file or directory
