mkdir: cannot create directory ‘CPAR2_204130.1-T_37_180_60/’: File exists
mkdir: cannot create directory ‘CPAR2_204130.1-T_37_180_60/seq/’: File exists
mkdir: cannot create directory ‘CPAR2_204130.1-T_37_180_60/tab’: File exists
mkdir: cannot create directory ‘CPAR2_204130.1-T_37_180_60/res’: File exists
mkdir: cannot create directory ‘CPAR2_204130.1-T_37_180_60/final’: File exists
Traceback (most recent call last):
  File "get_combined_score.py", line 1023, in <module>
    main()
  File "get_combined_score.py", line 699, in main
    rnn = open("%s.RNN.tab_tmp" %molname)
IOError: [Errno 2] No such file or directory: 'CPAR2_204130.1-T.RNN.tab_tmp'

real	0m14.257s
user	0m9.907s
sys	0m1.398s
mv: cannot stat '/gpfs/projects/bsc40/uchorostecki/software/nextPARS/bin/CPAR2_204130.1-T.RNN.tab': No such file or directory
mv: cannot stat '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/37_degrees/CPAR2_204130.1-T_37_180_60/seq/CPAR2_204130.1-T.outfile': No such file or directory
Traceback (most recent call last):
  File "/gpfs/projects/bsc40/uchorostecki/software/MultiFolds/scripts/sliding_windows_nextPARSE_score.py", line 58, in <module>
    main()
  File "/gpfs/projects/bsc40/uchorostecki/software/MultiFolds/scripts/sliding_windows_nextPARSE_score.py", line 54, in main
    process_tab(args.infile,int(args.window),int(args.step))
  File "/gpfs/projects/bsc40/uchorostecki/software/MultiFolds/scripts/sliding_windows_nextPARSE_score.py", line 29, in process_tab
    df = read_csv(tab_file,header=None,delimiter='\t',names = ['name', 'data'])
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: [Errno 2] File CPAR2_204130.1-T.RNN_NP_ONLY.csv does not exist: 'CPAR2_204130.1-T.RNN_NP_ONLY.csv'

real	0m0.089s
user	0m0.042s
sys	0m0.009s
./multifolds_cluster.sh: line 120: CPAR2_204130.1-T.fa: No such file or directory
split: cannot open 'CPAR2_204130.1-T.SHAPE' for reading: No such file or directory
ls: cannot access '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/37_degrees/CPAR2_204130.1-T_37_180_60/res/splited_*': No such file or directory
mv: cannot stat '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/37_degrees/CPAR2_204130.1-T_37_180_60/res/*_*.SHAPE': No such file or directory
mv: cannot stat '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/37_degrees/CPAR2_204130.1-T_37_180_60/res/*_*.fa': No such file or directory
ls: cannot access '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/37_degrees/CPAR2_204130.1-T_37_180_60/final/*SHAPE': No such file or directory
ls: cannot access '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/37_degrees/CPAR2_204130.1-T_37_180_60/final/*.ct': No such file or directory
