/gpfs/projects/bsc40/uchorostecki/software/nextPARS/bin/tabscorelib.py:452: RuntimeWarning: invalid value encountered in double_scalars
  return [x/(vMax*1.0)*normalizeTo for x in L]

real	0m2.102s
user	0m0.226s
sys	0m0.411s
mv: cannot stat '/gpfs/projects/bsc40/uchorostecki/software/nextPARS/bin/3UTR_long_SNCA.RNN.tab': No such file or directory
Traceback (most recent call last):
  File "/gpfs/projects/bsc40/uchorostecki/software/MultiFolds/scripts/sliding_windows_nextPARSE_score.py", line 58, in <module>
    main()
  File "/gpfs/projects/bsc40/uchorostecki/software/MultiFolds/scripts/sliding_windows_nextPARSE_score.py", line 54, in main
    process_tab(args.infile,int(args.window),int(args.step))
  File "/gpfs/projects/bsc40/uchorostecki/software/MultiFolds/scripts/sliding_windows_nextPARSE_score.py", line 29, in process_tab
    df = read_csv(tab_file,header=None,delimiter='\t',names = ['name', 'data'])
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: [Errno 2] File 3UTR_long_SNCA.RNN_NP_ONLY.csv does not exist: '3UTR_long_SNCA.RNN_NP_ONLY.csv'

real	0m0.056s
user	0m0.017s
sys	0m0.029s
split: cannot open '3UTR_long_SNCA.SHAPE' for reading: No such file or directory
ls: cannot access '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/3UTR_long_SNCA_180_60/res/splited_*': No such file or directory
mv: cannot stat '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/3UTR_long_SNCA_180_60/res/*_*.SHAPE': No such file or directory
ls: cannot access '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/3UTR_long_SNCA_180_60/final/*SHAPE': No such file or directory
ls: cannot access '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/3UTR_long_SNCA_180_60/final/*.ct': No such file or directory
